language: generic
sudo: required
services:
  - docker
    
before_install:
  - docker build -t robaczek/react-test -f ./client/Dockerfile.dev ./client/
    
script:
  - docker run -e CI=true robaczek/react-test npm run test -- --coverage

after_success:
  - docker build -t robaczek/multi-client ./client/
  - docker build -t robaczek/multi-nginx ./nginx/
  - docker build -t robaczek/multi-server ./server/
  - docker build -t robaczek/multi-worker ./worker/
# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
# Take images and push to docker hub  
  - docker push robaczek/multi-client
  - docker push robaczek/multi-nginx 
  - docker push robaczek/multi-server 
  - docker push robaczek/multi-worker 